<!--: spam
Content-Type: text/html

<body bgcolor="#f0f0f8"><font color="#f0f0f8" size="-5"> -->
<body bgcolor="#f0f0f8"><font color="#f0f0f8" size="-5"> --> -->
</font> </font> </font> </script> </object> </blockquote> </pre>
</table> </table> </table> </table> </table> </font> </font> </font><body bgcolor="#f0f0f8">
<table width="100%" cellspacing=0 cellpadding=2 border=0 summary="heading">
<tr bgcolor="#6622aa">
<td valign=bottom>&nbsp;<br>
<font color="#ffffff" face="helvetica, arial">&nbsp;<br><big><big><strong>&lt;type 'exceptions.UnicodeEncodeError'&gt;</strong></big></big></font></td
><td align=right valign=bottom
><font color="#ffffff" face="helvetica, arial">Python 2.7.3: /usr/bin/python<br>Fri May 26 10:09:22 2017</font></td></tr></table>
    
<p>A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.</p>
<table width="100%" cellspacing=0 cellpadding=0 border=0>
<tr><td bgcolor="#d8bbff"><big>&nbsp;</big><a href="file:///home/tobs/prosoar.de/util/bin/public/download_task.py">/home/tobs/prosoar.de/util/bin/public/download_task.py</a> in <strong><module></strong>()</td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;64</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
</tt></font></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;65</small>&nbsp;<br>
</tt></font></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;66</small>&nbsp;if&nbsp;__name__&nbsp;==&nbsp;'__main__':<br>
</tt></font></td></tr>
<tr><td bgcolor="#ffccee"><tt>=&gt;<small>&nbsp;&nbsp;&nbsp;67</small>&nbsp;&nbsp;&nbsp;main()<br>
</tt></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;68</small>&nbsp;<br>
</tt></font></td></tr>
<tr><td><small><font color="#909090"><strong>main</strong>&nbsp;= &lt;function main&gt;</font></small></td></tr></table>
<table width="100%" cellspacing=0 cellpadding=0 border=0>
<tr><td bgcolor="#d8bbff"><big>&nbsp;</big><a href="file:///home/tobs/prosoar.de/util/bin/public/download_task.py">/home/tobs/prosoar.de/util/bin/public/download_task.py</a> in <strong>main</strong>()</td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;61</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print&nbsp;"Content-disposition:&nbsp;attachment;&nbsp;filename="&nbsp;+&nbsp;taskname&nbsp;+&nbsp;".cup"<br>
</tt></font></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;62</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print<br>
</tt></font></td></tr>
<tr><td bgcolor="#ffccee"><tt>=&gt;<small>&nbsp;&nbsp;&nbsp;63</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print&nbsp;create_seeyou_task(task,&nbsp;taskname)<br>
</tt></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;64</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
</tt></font></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;65</small>&nbsp;<br>
</tt></font></td></tr>
<tr><td><small><font color="#909090"><em>global</em> <strong>create_seeyou_task</strong>&nbsp;= &lt;function create_seeyou_task&gt;, <strong>task</strong>&nbsp;= &lt;prosoar.task.task.Task instance&gt;, <strong>taskname</strong>&nbsp;= '536557'</font></small></td></tr></table><p><strong>&lt;type 'exceptions.UnicodeEncodeError'&gt;</strong>: 'ascii' codec can't encode character u'\xf6' in position 61: ordinal not in range(128)
<br><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>&nbsp;</tt>args&nbsp;=
('ascii', u'name,code,country,lat,lon,elev,style,rwdir,rwlen...1=25000m,A1=180<font color="#c040c0">\n</font>ObsZone=4,Style=3,R1=4000m,A1=180', 61, 62, 'ordinal not in range(128)')
<br><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>&nbsp;</tt>encoding&nbsp;=
'ascii'
<br><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>&nbsp;</tt>end&nbsp;=
62
<br><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>&nbsp;</tt>message&nbsp;=
''
<br><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>&nbsp;</tt>object&nbsp;=
u'name,code,country,lat,lon,elev,style,rwdir,rwlen...1=25000m,A1=180<font color="#c040c0">\n</font>ObsZone=4,Style=3,R1=4000m,A1=180'
<br><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>&nbsp;</tt>reason&nbsp;=
'ordinal not in range(128)'
<br><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>&nbsp;</tt>start&nbsp;=
61


<!-- The above is a description of an error in a Python program, formatted
     for a Web browser because the 'cgitb' module was enabled.  In case you
     are not reading this in a Web browser, here is the original traceback:

Traceback (most recent call last):
  File "download_task.py", line 67, in &lt;module&gt;
    main()
  File "download_task.py", line 63, in main
    print create_seeyou_task(task, taskname)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 61: ordinal not in range(128)

-->

